config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :marks
  resources :tests
  resources :courses
   
  root 'static#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :students, optional: true
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :students, optional: true
  belongs_to :tests, optional: true
  belongs_to :courses, optional: true
  # attr_accessible :course_id
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :marks
  has_many :tests 
  has_many :courses



end

app/models/test.rb
class Test < ApplicationRecord
  has_many :students
  has_many :courses

  attr_accessor :student_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
    # @tests = Test.all
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show, :edit, :update, :destroy]
  def index
    @marks = Mark.all
    # @tests = Test.all
    # @students = Student.all
  end
  def show
   @marks = Mark.find(params[:id])
  end
  def mark_test
    @mark_test = Mark.where(:student_id => student.id, :test_id => test.id).sum(:mark)
    # @mark_test = Mark.where(:student_id => s.id, :test_id => t.id).sum(:mark)
  end

  def set_mark
    @mark = Mark.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @students = Student.all
    @courses = Course.all
    @tests = Test.all
    # @marks = Marks.all
  end


  def weight_and_mark  
    @mark_test = Mark.where(:student_id => s.id, :test_id => t.id).sum(:mark)
    @weight_course =  Test.where(:course_id => c.id, :weight => t.weight, :id => t.id).sum(:weight) / 10 
    @weight_and_mark = (@mark_test * @weight_course) 
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
    @marks = Mark.where(:student_id => 1, :test_id => 1).sum(:mark)
    # @marks.test_id = @test.id
    @tests = Test.all
  end

  def show
    
  end
  def edit
  end

  def create
    @student = Student.new(student_params)
    # @student.student_id = current_student.id

    if @student.save
      redirect_to @student, notice: 'Student was created successfully'
    else
      render :new
    end
  end
  def student_params
    params.require(:student).permit(:id, :name)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]
  def index
    @tests = Test.all
    # @marks = Mark.where(:student_id => 1, :test_id => 1).sum(:mark)
    
    
    @students = Student.all

    # @weight_course =  Test.where(:course_id => c.id, :weight => t.weight, :id => t.id).sum(:weight) / 10
    # @mark_test = Mark.where(:student_id => s.id, :test_id => t.id).sum(:mark)
    # @weight_and_mark = (@mark_test * @weight_course).to_f
    
  end

  def weight_course
    @weight_course =  Test.where(:course_id => course.id, :weight => test.weight, :id => test.id).sum(:weight) / 10
    # @weight_course =  Test.where(:course_id => c.id, :weight => t.weight, :id => t.id).sum(:weight) / 10 
  end

  def test_params
    params.require(:test).permit(:id, :course_id, :student_id)
  end

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
  
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/courses/_course.html.erb
<tr>
  <td>
   <%= course.id %>
  </td>
  <td>
    <%= course.name %>
  </td>  
  <td>
    <%= course.teacher %>
  </td>
</tr>

app/views/courses/index.html.erb
<div class="container">
  <h3>Courses</h3>
  <div class="row"> 
    <div class="col-md-4 col-sm-4"> 
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>
              Id
            </th>
            <th>
              Name
            </th>
            <th>
              Teacher
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render @courses %>
        </tbody>
      </table>
    </div> 
  </div> 
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentReport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
    

  </body>
</html>

app/views/marks/_mark.html.erb
<tr>
  <td>
   <%= mark.test_id %>
  </td>
  <td>
    <%= mark.student_id %>
  </td>
  <td>
    <%= mark.mark %>
  </td>
  
</tr>

app/views/marks/index.html.erb
<div class="container">
  <h3>Marks </h3>
  <div class="row"> 
    <div class="col-md-4 col-sm-4"> 
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>
              Test id
            </th>
            <th>
              Student id
            </th>
            <th>
              Mark
            </th>
            <th>
              Weight
            </th>
          </tr>
        </thead>
        <tbody>
          <%= render @marks %>
        </tbody>
      </table>
    </div> 
  </div> 
 
</div>

app/views/shared/_nav.html.erb
<div class='logo'>
  <h1>Report Page</h1>
</div>


  <ul class="custom-nav nav nav-tabs">
     <li class="">
       <%= link_to "Report", root_path %>
     </li>
     <li class="">
       <%= link_to "Students", students_path %>
     </li>

     <li class="">
       <%= link_to "Tests", tests_path, id: "new_post_from_nav" %>
     </li>

     <li class="">
       <%= link_to "Marks", marks_path %>
     </li>
     <li class="">
       <%= link_to "Courses", courses_path %>
     </li>
  </ul>

app/views/students/_student.html.erb
<tr>
  <td>
   <%= student.id %>
  </td>
  <td>
    <%= student.name %>
  </td>
  
</tr>

app/views/students/index.html.erb
<div class="container">
  <h3>Students </h3>
  <div class="row"> 
    <div class="col-md-4 col-sm-4"> 
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>
              Id
            </th>
            <th>
              Name
            </th>
            
          </tr>
        </thead>
        <tbody>
          <%= render @students %>
        </tbody>
      </table>
    </div> 
  </div> 
  
</div>